/*
###############################################################
#  Generated by:      Cadence Encounter 14.28-s033_1
#  OS:                Linux x86_64(Host ID cobalt.clear.rice.edu)
#  Generated on:      Wed Mar  1 23:08:56 2023
#  Design:            CORDIC_TOP
#  Command:           saveNetlist final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : N-2017.09-SP2
// Date      : Wed Mar  1 22:26:28 2023
/////////////////////////////////////////////////////////////
module CORDIC_TOP (
	clka, 
	clkb, 
	reset, 
	start, 
	cordic_mode, 
	in_port0, 
	in_port1, 
	out_port0, 
	out_port1, 
	done);
   input clka;
   input clkb;
   input reset;
   input start;
   input cordic_mode;
   input [7:0] in_port0;
   input [7:0] in_port1;
   output [7:0] out_port0;
   output [7:0] out_port1;
   output done;

   // Internal wires
   wire counter_rst;
   wire \fsm/n36 ;
   wire \fsm/n35 ;
   wire \fsm/n34 ;
   wire \fsm/n33 ;
   wire \fsm/n32 ;
   wire \fsm/n31 ;
   wire \fsm/n30 ;
   wire \fsm/n29 ;
   wire \fsm/n28 ;
   wire \fsm/n27 ;
   wire \fsm/n26 ;
   wire \fsm/n25 ;
   wire \fsm/n24 ;
   wire \fsm/n23 ;
   wire \fsm/n22 ;
   wire \fsm/n21 ;
   wire \fsm/n20 ;
   wire \fsm/n19 ;
   wire \fsm/n18 ;
   wire \fsm/n17 ;
   wire \fsm/n16 ;
   wire \fsm/n15 ;
   wire \fsm/n14 ;
   wire \fsm/n13 ;
   wire \fsm/n12 ;
   wire \fsm/N45 ;
   wire \fsm/N44 ;
   wire \fsm/N43 ;
   wire \fsm/state[0] ;
   wire \fsm/state[1] ;
   wire \fsm/state[2] ;
   wire \dp/n197 ;
   wire \dp/n196 ;
   wire \dp/n195 ;
   wire \dp/n194 ;
   wire \dp/n193 ;
   wire \dp/n192 ;
   wire \dp/n191 ;
   wire \dp/n190 ;
   wire \dp/n189 ;
   wire \dp/n188 ;
   wire \dp/n187 ;
   wire \dp/n186 ;
   wire \dp/n185 ;
   wire \dp/n184 ;
   wire \dp/n183 ;
   wire \dp/n182 ;
   wire \dp/n181 ;
   wire \dp/n180 ;
   wire \dp/n179 ;
   wire \dp/n178 ;
   wire \dp/n177 ;
   wire \dp/n176 ;
   wire \dp/n175 ;
   wire \dp/n174 ;
   wire \dp/n173 ;
   wire \dp/n172 ;
   wire \dp/n171 ;
   wire \dp/n170 ;
   wire \dp/n169 ;
   wire \dp/n168 ;
   wire \dp/n167 ;
   wire \dp/n166 ;
   wire \dp/n165 ;
   wire \dp/n164 ;
   wire \dp/n163 ;
   wire \dp/n162 ;
   wire \dp/n161 ;
   wire \dp/n160 ;
   wire \dp/n159 ;
   wire \dp/n158 ;
   wire \dp/n157 ;
   wire \dp/n156 ;
   wire \dp/n155 ;
   wire \dp/n154 ;
   wire \dp/n153 ;
   wire \dp/n152 ;
   wire \dp/n151 ;
   wire \dp/n150 ;
   wire \dp/n149 ;
   wire \dp/n148 ;
   wire \dp/n147 ;
   wire \dp/n146 ;
   wire \dp/n145 ;
   wire \dp/n144 ;
   wire \dp/n143 ;
   wire \dp/n142 ;
   wire \dp/n141 ;
   wire \dp/n140 ;
   wire \dp/n139 ;
   wire \dp/n138 ;
   wire \dp/n137 ;
   wire \dp/n136 ;
   wire \dp/n135 ;
   wire \dp/n134 ;
   wire \dp/n133 ;
   wire \dp/n132 ;
   wire \dp/n131 ;
   wire \dp/n130 ;
   wire \dp/n129 ;
   wire \dp/n128 ;
   wire \dp/n127 ;
   wire \dp/n126 ;
   wire \dp/n125 ;
   wire \dp/n124 ;
   wire \dp/n123 ;
   wire \dp/n122 ;
   wire \dp/n121 ;
   wire \dp/n120 ;
   wire \dp/n119 ;
   wire \dp/n118 ;
   wire \dp/n117 ;
   wire \dp/n116 ;
   wire \dp/n115 ;
   wire \dp/n114 ;
   wire \dp/n113 ;
   wire \dp/n112 ;
   wire \dp/n111 ;
   wire \dp/n110 ;
   wire \dp/n109 ;
   wire \dp/n108 ;
   wire \dp/n107 ;
   wire \dp/n106 ;
   wire \dp/n105 ;
   wire \dp/n104 ;
   wire \dp/n103 ;
   wire \dp/n102 ;
   wire \dp/n99 ;
   wire \dp/n98 ;
   wire \dp/n97 ;
   wire \dp/n96 ;
   wire \dp/n95 ;
   wire \dp/n94 ;
   wire \dp/n93 ;
   wire \dp/n92 ;
   wire \dp/n91 ;
   wire \dp/N202 ;
   wire \dp/N201 ;
   wire \dp/N200 ;
   wire \dp/N199 ;
   wire \dp/N198 ;
   wire \dp/N197 ;
   wire \dp/N196 ;
   wire \dp/N195 ;
   wire \dp/N194 ;
   wire \dp/N193 ;
   wire \dp/N192 ;
   wire \dp/N191 ;
   wire \dp/N190 ;
   wire \dp/N189 ;
   wire \dp/N188 ;
   wire \dp/N187 ;
   wire \dp/N178 ;
   wire \dp/N177 ;
   wire \dp/N176 ;
   wire \dp/N175 ;
   wire \dp/N174 ;
   wire \dp/N173 ;
   wire \dp/N172 ;
   wire \dp/N171 ;
   wire \dp/N162 ;
   wire \dp/N161 ;
   wire \dp/N160 ;
   wire \dp/N159 ;
   wire \dp/N158 ;
   wire \dp/N157 ;
   wire \dp/N156 ;
   wire \dp/N155 ;
   wire \dp/N154 ;
   wire \dp/N153 ;
   wire \dp/N152 ;
   wire \dp/N151 ;
   wire \dp/N150 ;
   wire \dp/N149 ;
   wire \dp/N148 ;
   wire \dp/N147 ;
   wire \dp/N146 ;
   wire \dp/N145 ;
   wire \dp/N144 ;
   wire \dp/N143 ;
   wire \dp/N142 ;
   wire \dp/N141 ;
   wire \dp/N140 ;
   wire \dp/N139 ;
   wire \dp/N138 ;
   wire \dp/N137 ;
   wire \dp/N136 ;
   wire \dp/N135 ;
   wire \dp/N134 ;
   wire \dp/N133 ;
   wire \dp/N132 ;
   wire \dp/N131 ;
   wire \dp/N130 ;
   wire \dp/N129 ;
   wire \dp/N128 ;
   wire \dp/N127 ;
   wire \dp/N126 ;
   wire \dp/N125 ;
   wire \dp/N124 ;
   wire \dp/N123 ;
   wire \dp/N119 ;
   wire \dp/N118 ;
   wire \dp/N117 ;
   wire \dp/N116 ;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire [3:0] counter;
   wire [1:0] in_mux_ctl;
   wire [2:0] \fsm/next_state ;
   wire [7:0] \dp/x_regb ;
   wire [7:0] \dp/theta_rega ;
   wire [7:0] \dp/y_rega ;
   wire [7:0] \dp/x_rega ;
   wire [3:0] \dp/next_counter ;
   wire [7:0] \dp/theta_regb ;
   wire [5:0] \dp/ROM_VALUE ;
   wire [8:0] \dp/sub_72/carry ;
   wire [7:1] \dp/add_73/carry ;
   wire [8:0] \dp/sub_74/carry ;
   wire [7:1] \dp/add_77/carry ;
   wire [8:0] \dp/sub_78/carry ;
   wire [7:1] \dp/add_79/carry ;

   NAND2X1 \fsm/U41  (.Y(\fsm/n28 ),
	.B(n64),
	.A(n68));
   NAND2X1 \fsm/U40  (.Y(\fsm/n25 ),
	.B(n66),
	.A(n24));
   NAND2X1 \fsm/U39  (.Y(\fsm/n29 ),
	.B(n23),
	.A(start));
   NOR2X1 \fsm/U38  (.Y(\fsm/N43 ),
	.B(\fsm/n29 ),
	.A(\fsm/n28 ));
   OAI21X1 \fsm/U37  (.Y(\fsm/n23 ),
	.C(n64),
	.B(\fsm/state[0] ),
	.A(\fsm/n27 ));
   NOR2X1 \fsm/U36  (.Y(\fsm/n26 ),
	.B(counter[1]),
	.A(counter[2]));
   NAND3X1 \fsm/U35  (.Y(\fsm/n22 ),
	.C(\fsm/n26 ),
	.B(n123),
	.A(counter[3]));
   NAND3X1 \fsm/U34  (.Y(\fsm/n24 ),
	.C(\fsm/state[1] ),
	.B(n68),
	.A(\fsm/n22 ));
   AOI21X1 \fsm/U33  (.Y(\fsm/N44 ),
	.C(\fsm/n25 ),
	.B(\fsm/n24 ),
	.A(\fsm/n23 ));
   NAND3X1 \fsm/U32  (.Y(\fsm/n19 ),
	.C(n24),
	.B(n64),
	.A(n68));
   NAND2X1 \fsm/U31  (.Y(\fsm/n20 ),
	.B(\fsm/n22 ),
	.A(\fsm/state[2] ));
   NAND3X1 \fsm/U30  (.Y(\fsm/n21 ),
	.C(n23),
	.B(\fsm/state[1] ),
	.A(\fsm/state[0] ));
   OAI21X1 \fsm/U29  (.Y(\fsm/N45 ),
	.C(\fsm/n21 ),
	.B(\fsm/n20 ),
	.A(\fsm/n19 ));
   OAI21X1 \fsm/U28  (.Y(\fsm/n12 ),
	.C(\fsm/next_state [2]),
	.B(\fsm/next_state [0]),
	.A(\fsm/next_state [1]));
   OAI22X1 \fsm/U27  (.Y(\fsm/n36 ),
	.D(n68),
	.C(\fsm/n12 ),
	.B(n65),
	.A(n63));
   NAND2X1 \fsm/U26  (.Y(\fsm/n16 ),
	.B(n62),
	.A(n65));
   AOI21X1 \fsm/U25  (.Y(\fsm/n35 ),
	.C(n67),
	.B(n66),
	.A(\fsm/n16 ));
   OAI22X1 \fsm/U24  (.Y(\fsm/n34 ),
	.D(n64),
	.C(\fsm/n12 ),
	.B(n62),
	.A(n63));
   NAND2X1 \fsm/U23  (.Y(\fsm/n18 ),
	.B(n63),
	.A(counter_rst));
   OAI21X1 \fsm/U22  (.Y(\fsm/n33 ),
	.C(\fsm/n18 ),
	.B(n65),
	.A(n63));
   NAND3X1 \fsm/U21  (.Y(\fsm/n17 ),
	.C(done),
	.B(\fsm/n16 ),
	.A(\fsm/next_state [2]));
   OAI21X1 \fsm/U20  (.Y(\fsm/n32 ),
	.C(\fsm/n17 ),
	.B(\fsm/n16 ),
	.A(\fsm/next_state [2]));
   NAND2X1 \fsm/U19  (.Y(\fsm/n14 ),
	.B(n67),
	.A(\fsm/next_state [1]));
   NAND3X1 \fsm/U18  (.Y(\fsm/n15 ),
	.C(in_mux_ctl[1]),
	.B(\fsm/n16 ),
	.A(\fsm/next_state [2]));
   OAI21X1 \fsm/U17  (.Y(\fsm/n31 ),
	.C(\fsm/n15 ),
	.B(\fsm/n14 ),
	.A(n65));
   OAI21X1 \fsm/U16  (.Y(\fsm/n13 ),
	.C(n65),
	.B(n67),
	.A(n62));
   OAI21X1 \fsm/U15  (.Y(\fsm/n30 ),
	.C(\fsm/n13 ),
	.B(n57),
	.A(\fsm/n12 ));
   AND2X2 \fsm/U3  (.Y(\fsm/n27 ),
	.B(cordic_mode),
	.A(start));
   DFFNEGX1 \fsm/in_mux_ctl_reg[0]  (.Q(in_mux_ctl[0]),
	.D(\fsm/n30 ),
	.CLK(clkb));
   DFFNEGX1 \fsm/in_mux_ctl_reg[1]  (.Q(in_mux_ctl[1]),
	.D(\fsm/n31 ),
	.CLK(clkb));
   DFFNEGX1 \fsm/counter_rst_reg  (.Q(counter_rst),
	.D(\fsm/n33 ),
	.CLK(n21));
   DFFNEGX1 \fsm/counter_hold_reg  (.Q(done),
	.D(\fsm/n32 ),
	.CLK(clkb));
   DFFNEGX1 \fsm/next_state_reg[1]  (.Q(\fsm/next_state [1]),
	.D(\fsm/N44 ),
	.CLK(clka));
   DFFNEGX1 \fsm/state_reg[1]  (.Q(\fsm/state[1] ),
	.D(\fsm/n34 ),
	.CLK(n20));
   DFFNEGX1 \fsm/next_state_reg[0]  (.Q(\fsm/next_state [0]),
	.D(\fsm/N43 ),
	.CLK(clka));
   DFFNEGX1 \fsm/state_reg[2]  (.Q(\fsm/state[2] ),
	.D(\fsm/n35 ),
	.CLK(clkb));
   DFFNEGX1 \fsm/next_state_reg[2]  (.Q(\fsm/next_state [2]),
	.D(\fsm/N45 ),
	.CLK(clka));
   DFFNEGX1 \fsm/state_reg[0]  (.Q(\fsm/state[0] ),
	.D(\fsm/n36 ),
	.CLK(clkb));
   XOR2X1 \dp/U197  (.Y(\dp/n170 ),
	.B(counter_rst),
	.A(done));
   NAND3X1 \dp/U196  (.Y(\dp/n173 ),
	.C(\dp/next_counter [0]),
	.B(n59),
	.A(done));
   OAI21X1 \dp/U195  (.Y(\dp/N116 ),
	.C(\dp/n173 ),
	.B(\dp/n170 ),
	.A(\dp/next_counter [0]));
   AOI22X1 \dp/U194  (.Y(\dp/n171 ),
	.D(n61),
	.C(n124),
	.B(done),
	.A(n59));
   NAND3X1 \dp/U193  (.Y(\dp/n172 ),
	.C(\dp/next_counter [0]),
	.B(n122),
	.A(n61));
   OAI21X1 \dp/U192  (.Y(\dp/N117 ),
	.C(\dp/n172 ),
	.B(n122),
	.A(\dp/n171 ));
   OAI21X1 \dp/U191  (.Y(\dp/n169 ),
	.C(\dp/n171 ),
	.B(\dp/n170 ),
	.A(\dp/next_counter [1]));
   NAND3X1 \dp/U190  (.Y(\dp/n168 ),
	.C(\dp/next_counter [1]),
	.B(\dp/next_counter [0]),
	.A(n61));
   OAI22X1 \dp/U189  (.Y(\dp/N118 ),
	.D(\dp/n168 ),
	.C(\dp/next_counter [2]),
	.B(n121),
	.A(n58));
   AOI21X1 \dp/U188  (.Y(\dp/n166 ),
	.C(\dp/n169 ),
	.B(n121),
	.A(n61));
   NAND3X1 \dp/U187  (.Y(\dp/n167 ),
	.C(\dp/next_counter [2]),
	.B(n114),
	.A(n60));
   OAI21X1 \dp/U186  (.Y(\dp/N119 ),
	.C(\dp/n167 ),
	.B(n114),
	.A(\dp/n166 ));
   OAI22X1 \dp/U185  (.Y(\dp/n142 ),
	.D(cordic_mode),
	.C(\dp/theta_rega [7]),
	.B(n111),
	.A(n7));
   AOI22X1 \dp/U184  (.Y(\dp/n165 ),
	.D(n13),
	.C(\dp/N131 ),
	.B(n18),
	.A(\dp/N171 ));
   AOI22X1 \dp/U183  (.Y(\dp/n164 ),
	.D(n13),
	.C(\dp/N132 ),
	.B(n18),
	.A(\dp/N172 ));
   AOI22X1 \dp/U182  (.Y(\dp/n163 ),
	.D(n13),
	.C(\dp/N133 ),
	.B(n18),
	.A(\dp/N173 ));
   AOI22X1 \dp/U181  (.Y(\dp/n162 ),
	.D(n13),
	.C(\dp/N134 ),
	.B(n18),
	.A(\dp/N174 ));
   AOI22X1 \dp/U180  (.Y(\dp/n161 ),
	.D(n13),
	.C(\dp/N135 ),
	.B(n17),
	.A(\dp/N175 ));
   AOI22X1 \dp/U179  (.Y(\dp/n160 ),
	.D(n13),
	.C(\dp/N136 ),
	.B(n17),
	.A(\dp/N176 ));
   AOI22X1 \dp/U178  (.Y(\dp/n159 ),
	.D(n13),
	.C(\dp/N137 ),
	.B(n17),
	.A(\dp/N177 ));
   AOI22X1 \dp/U177  (.Y(\dp/n158 ),
	.D(n13),
	.C(\dp/N138 ),
	.B(n17),
	.A(\dp/N178 ));
   AOI22X1 \dp/U176  (.Y(\dp/n157 ),
	.D(n13),
	.C(\dp/N147 ),
	.B(n17),
	.A(\dp/N187 ));
   AOI22X1 \dp/U175  (.Y(\dp/n156 ),
	.D(n13),
	.C(\dp/N148 ),
	.B(n17),
	.A(\dp/N188 ));
   AOI22X1 \dp/U174  (.Y(\dp/n155 ),
	.D(n13),
	.C(\dp/N149 ),
	.B(n17),
	.A(\dp/N189 ));
   AOI22X1 \dp/U173  (.Y(\dp/n154 ),
	.D(n13),
	.C(\dp/N150 ),
	.B(n16),
	.A(\dp/N190 ));
   AOI22X1 \dp/U172  (.Y(\dp/n153 ),
	.D(n13),
	.C(\dp/N151 ),
	.B(n16),
	.A(\dp/N191 ));
   AOI22X1 \dp/U171  (.Y(\dp/n152 ),
	.D(\dp/n142 ),
	.C(\dp/N152 ),
	.B(n16),
	.A(\dp/N192 ));
   AOI22X1 \dp/U170  (.Y(\dp/n151 ),
	.D(\dp/n142 ),
	.C(\dp/N153 ),
	.B(n16),
	.A(\dp/N193 ));
   AOI22X1 \dp/U169  (.Y(\dp/n150 ),
	.D(\dp/n142 ),
	.C(\dp/N154 ),
	.B(n16),
	.A(\dp/N194 ));
   AOI22X1 \dp/U168  (.Y(\dp/n149 ),
	.D(\dp/n142 ),
	.C(\dp/N155 ),
	.B(n16),
	.A(\dp/N195 ));
   AOI22X1 \dp/U167  (.Y(\dp/n148 ),
	.D(\dp/n142 ),
	.C(\dp/N156 ),
	.B(n16),
	.A(\dp/N196 ));
   AOI22X1 \dp/U166  (.Y(\dp/n147 ),
	.D(\dp/n142 ),
	.C(\dp/N157 ),
	.B(n15),
	.A(\dp/N197 ));
   AOI22X1 \dp/U165  (.Y(\dp/n146 ),
	.D(\dp/n142 ),
	.C(\dp/N158 ),
	.B(n15),
	.A(\dp/N198 ));
   AOI22X1 \dp/U164  (.Y(\dp/n145 ),
	.D(\dp/n142 ),
	.C(\dp/N159 ),
	.B(n15),
	.A(\dp/N199 ));
   AOI22X1 \dp/U163  (.Y(\dp/n144 ),
	.D(\dp/n142 ),
	.C(\dp/N160 ),
	.B(n14),
	.A(\dp/N200 ));
   AOI22X1 \dp/U162  (.Y(\dp/n143 ),
	.D(\dp/n142 ),
	.C(\dp/N161 ),
	.B(n14),
	.A(\dp/N201 ));
   AOI22X1 \dp/U161  (.Y(\dp/n141 ),
	.D(\dp/n142 ),
	.C(\dp/N162 ),
	.B(n14),
	.A(\dp/N202 ));
   NAND2X1 \dp/U160  (.Y(\dp/n138 ),
	.B(n11),
	.A(n9));
   NAND2X1 \dp/U159  (.Y(\dp/n137 ),
	.B(n10),
	.A(counter[1]));
   NAND2X1 \dp/U158  (.Y(\dp/n140 ),
	.B(n10),
	.A(n123));
   NAND3X1 \dp/U157  (.Y(\dp/n133 ),
	.C(counter[0]),
	.B(n10),
	.A(n9));
   OAI21X1 \dp/U156  (.Y(\dp/n139 ),
	.C(\dp/n133 ),
	.B(\dp/n140 ),
	.A(n9));
   NAND2X1 \dp/U155  (.Y(\dp/n135 ),
	.B(n11),
	.A(\dp/n139 ));
   OAI21X1 \dp/U154  (.Y(\dp/ROM_VALUE [2]),
	.C(\dp/n135 ),
	.B(\dp/n137 ),
	.A(counter[3]));
   OAI21X1 \dp/U153  (.Y(\dp/ROM_VALUE [0]),
	.C(n117),
	.B(\dp/n138 ),
	.A(n10));
   OAI21X1 \dp/U152  (.Y(\dp/n136 ),
	.C(\dp/n137 ),
	.B(counter[0]),
	.A(counter[1]));
   NOR2X1 \dp/U151  (.Y(\dp/n134 ),
	.B(counter[2]),
	.A(counter[3]));
   NAND3X1 \dp/U150  (.Y(\dp/n132 ),
	.C(\dp/n134 ),
	.B(n9),
	.A(n123));
   OAI21X1 \dp/U149  (.Y(\dp/ROM_VALUE [4]),
	.C(\dp/n132 ),
	.B(\dp/n133 ),
	.A(counter[3]));
   NOR2X1 \dp/U146  (.Y(\dp/n107 ),
	.B(n57),
	.A(\dp/n124 ));
   NOR2X1 \dp/U145  (.Y(\dp/n106 ),
	.B(\dp/n107 ),
	.A(\dp/n124 ));
   AOI22X1 \dp/U144  (.Y(\dp/n131 ),
	.D(in_port0[0]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [0]));
   OAI21X1 \dp/U143  (.Y(\dp/n197 ),
	.C(\dp/n131 ),
	.B(n113),
	.A(n8));
   AOI22X1 \dp/U142  (.Y(\dp/n130 ),
	.D(in_port0[1]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [1]));
   OAI21X1 \dp/U141  (.Y(\dp/n196 ),
	.C(\dp/n130 ),
	.B(n73),
	.A(n8));
   AOI22X1 \dp/U140  (.Y(\dp/n129 ),
	.D(in_port0[2]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [2]));
   OAI21X1 \dp/U139  (.Y(\dp/n195 ),
	.C(\dp/n129 ),
	.B(n72),
	.A(n8));
   AOI22X1 \dp/U138  (.Y(\dp/n128 ),
	.D(in_port0[3]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [3]));
   OAI21X1 \dp/U137  (.Y(\dp/n194 ),
	.C(\dp/n128 ),
	.B(n71),
	.A(n8));
   AOI22X1 \dp/U136  (.Y(\dp/n127 ),
	.D(in_port0[4]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [4]));
   OAI21X1 \dp/U135  (.Y(\dp/n193 ),
	.C(\dp/n127 ),
	.B(n70),
	.A(n8));
   AOI22X1 \dp/U134  (.Y(\dp/n126 ),
	.D(in_port0[5]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [5]));
   OAI21X1 \dp/U133  (.Y(\dp/n192 ),
	.C(\dp/n126 ),
	.B(n69),
	.A(n8));
   AOI22X1 \dp/U132  (.Y(\dp/n125 ),
	.D(in_port0[6]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [6]));
   OAI21X1 \dp/U131  (.Y(\dp/n191 ),
	.C(\dp/n125 ),
	.B(n74),
	.A(n8));
   AOI22X1 \dp/U130  (.Y(\dp/n123 ),
	.D(in_port0[7]),
	.C(\dp/n106 ),
	.B(\dp/n124 ),
	.A(\dp/theta_regb [7]));
   OAI21X1 \dp/U129  (.Y(\dp/n190 ),
	.C(\dp/n123 ),
	.B(n112),
	.A(n8));
   AOI22X1 \dp/U128  (.Y(\dp/n122 ),
	.D(n12),
	.C(out_port1[0]),
	.B(n1),
	.A(in_port1[0]));
   OAI21X1 \dp/U127  (.Y(\dp/n189 ),
	.C(\dp/n122 ),
	.B(n105),
	.A(n8));
   AOI22X1 \dp/U126  (.Y(\dp/n121 ),
	.D(n12),
	.C(out_port1[1]),
	.B(n1),
	.A(in_port1[1]));
   OAI21X1 \dp/U125  (.Y(\dp/n188 ),
	.C(\dp/n121 ),
	.B(n104),
	.A(n8));
   AOI22X1 \dp/U124  (.Y(\dp/n120 ),
	.D(n12),
	.C(out_port1[2]),
	.B(n1),
	.A(in_port1[2]));
   OAI21X1 \dp/U123  (.Y(\dp/n187 ),
	.C(\dp/n120 ),
	.B(n103),
	.A(n8));
   AOI22X1 \dp/U122  (.Y(\dp/n119 ),
	.D(n12),
	.C(out_port1[3]),
	.B(n1),
	.A(in_port1[3]));
   OAI21X1 \dp/U121  (.Y(\dp/n186 ),
	.C(\dp/n119 ),
	.B(n102),
	.A(n8));
   AOI22X1 \dp/U120  (.Y(\dp/n118 ),
	.D(n12),
	.C(out_port1[4]),
	.B(n1),
	.A(in_port1[4]));
   OAI21X1 \dp/U119  (.Y(\dp/n185 ),
	.C(\dp/n118 ),
	.B(n101),
	.A(n8));
   AOI22X1 \dp/U118  (.Y(\dp/n117 ),
	.D(n12),
	.C(out_port1[5]),
	.B(n1),
	.A(in_port1[5]));
   OAI21X1 \dp/U117  (.Y(\dp/n184 ),
	.C(\dp/n117 ),
	.B(n100),
	.A(n8));
   AOI22X1 \dp/U116  (.Y(\dp/n116 ),
	.D(n12),
	.C(out_port1[6]),
	.B(n1),
	.A(in_port1[6]));
   OAI21X1 \dp/U115  (.Y(\dp/n183 ),
	.C(\dp/n116 ),
	.B(n108),
	.A(n8));
   AOI22X1 \dp/U114  (.Y(\dp/n115 ),
	.D(n12),
	.C(out_port1[7]),
	.B(n1),
	.A(in_port1[7]));
   OAI21X1 \dp/U113  (.Y(\dp/n182 ),
	.C(\dp/n115 ),
	.B(n111),
	.A(n8));
   AOI22X1 \dp/U112  (.Y(\dp/n114 ),
	.D(\dp/x_regb [0]),
	.C(n12),
	.B(n1),
	.A(in_port0[0]));
   OAI21X1 \dp/U111  (.Y(\dp/n181 ),
	.C(\dp/n114 ),
	.B(n88),
	.A(n8));
   AOI22X1 \dp/U110  (.Y(\dp/n112 ),
	.D(\dp/n107 ),
	.C(\dp/x_rega [1]),
	.B(n1),
	.A(in_port0[1]));
   NOR2X1 \dp/U109  (.Y(\dp/n105 ),
	.B(n1),
	.A(\dp/n107 ));
   AOI21X1 \dp/U108  (.Y(\dp/n113 ),
	.C(\dp/n106 ),
	.B(\dp/x_regb [1]),
	.A(\dp/n105 ));
   NAND2X1 \dp/U107  (.Y(\dp/n180 ),
	.B(\dp/n113 ),
	.A(\dp/n112 ));
   AOI22X1 \dp/U106  (.Y(\dp/n110 ),
	.D(\dp/n107 ),
	.C(\dp/x_rega [2]),
	.B(n1),
	.A(in_port0[2]));
   AOI21X1 \dp/U105  (.Y(\dp/n111 ),
	.C(\dp/n106 ),
	.B(\dp/x_regb [2]),
	.A(\dp/n105 ));
   NAND2X1 \dp/U104  (.Y(\dp/n179 ),
	.B(\dp/n111 ),
	.A(\dp/n110 ));
   AOI22X1 \dp/U103  (.Y(\dp/n109 ),
	.D(\dp/x_regb [3]),
	.C(n12),
	.B(n1),
	.A(in_port0[3]));
   OAI21X1 \dp/U102  (.Y(\dp/n178 ),
	.C(\dp/n109 ),
	.B(n87),
	.A(n8));
   AOI22X1 \dp/U101  (.Y(\dp/n108 ),
	.D(\dp/x_regb [4]),
	.C(n12),
	.B(n1),
	.A(in_port0[4]));
   OAI21X1 \dp/U100  (.Y(\dp/n177 ),
	.C(\dp/n108 ),
	.B(n86),
	.A(n8));
   AOI22X1 \dp/U99  (.Y(\dp/n103 ),
	.D(\dp/n107 ),
	.C(\dp/x_rega [5]),
	.B(n1),
	.A(in_port0[5]));
   AOI21X1 \dp/U98  (.Y(\dp/n104 ),
	.C(\dp/n106 ),
	.B(\dp/x_regb [5]),
	.A(\dp/n105 ));
   NAND2X1 \dp/U97  (.Y(\dp/n176 ),
	.B(\dp/n104 ),
	.A(\dp/n103 ));
   AOI22X1 \dp/U96  (.Y(\dp/n102 ),
	.D(\dp/x_regb [6]),
	.C(n12),
	.B(n1),
	.A(in_port0[6]));
   OAI21X1 \dp/U95  (.Y(\dp/n175 ),
	.C(\dp/n102 ),
	.B(n85),
	.A(n8));
   AOI22X1 \dp/U94  (.Y(\dp/n99 ),
	.D(\dp/x_regb [7]),
	.C(n12),
	.B(n1),
	.A(in_port0[7]));
   OAI21X1 \dp/U93  (.Y(\dp/n174 ),
	.C(\dp/n99 ),
	.B(n91),
	.A(n8));
   AOI22X1 \dp/U92  (.Y(\dp/n98 ),
	.D(\dp/x_regb [0]),
	.C(n7),
	.B(\dp/theta_regb [0]),
	.A(cordic_mode));
   AOI22X1 \dp/U91  (.Y(\dp/n97 ),
	.D(\dp/x_regb [1]),
	.C(n7),
	.B(\dp/theta_regb [1]),
	.A(cordic_mode));
   AOI22X1 \dp/U90  (.Y(\dp/n96 ),
	.D(\dp/x_regb [2]),
	.C(n7),
	.B(\dp/theta_regb [2]),
	.A(cordic_mode));
   AOI22X1 \dp/U89  (.Y(\dp/n95 ),
	.D(\dp/x_regb [3]),
	.C(n7),
	.B(\dp/theta_regb [3]),
	.A(cordic_mode));
   AOI22X1 \dp/U88  (.Y(\dp/n94 ),
	.D(\dp/x_regb [4]),
	.C(n7),
	.B(\dp/theta_regb [4]),
	.A(cordic_mode));
   AOI22X1 \dp/U87  (.Y(\dp/n93 ),
	.D(\dp/x_regb [5]),
	.C(n7),
	.B(\dp/theta_regb [5]),
	.A(cordic_mode));
   AOI22X1 \dp/U86  (.Y(\dp/n92 ),
	.D(\dp/x_regb [6]),
	.C(n7),
	.B(\dp/theta_regb [6]),
	.A(cordic_mode));
   AOI22X1 \dp/U85  (.Y(\dp/n91 ),
	.D(\dp/x_regb [7]),
	.C(n7),
	.B(\dp/theta_regb [7]),
	.A(cordic_mode));
   AND2X2 \dp/U4  (.Y(\dp/ROM_VALUE [1]),
	.B(n11),
	.A(\dp/n136 ));
   DFFNEGX1 \dp/theta_rega_reg[5]  (.Q(\dp/theta_rega [5]),
	.D(\dp/n192 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[5]  (.Q(\dp/theta_regb [5]),
	.D(n46),
	.CLK(clkb));
   DFFNEGX1 \dp/theta_rega_reg[4]  (.Q(\dp/theta_rega [4]),
	.D(\dp/n193 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[4]  (.Q(\dp/theta_regb [4]),
	.D(n45),
	.CLK(clkb));
   DFFNEGX1 \dp/theta_rega_reg[3]  (.Q(\dp/theta_rega [3]),
	.D(\dp/n194 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[3]  (.Q(\dp/theta_regb [3]),
	.D(n44),
	.CLK(n21));
   DFFNEGX1 \dp/theta_rega_reg[2]  (.Q(\dp/theta_rega [2]),
	.D(\dp/n195 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[2]  (.Q(\dp/theta_regb [2]),
	.D(n43),
	.CLK(n21));
   DFFNEGX1 \dp/theta_rega_reg[1]  (.Q(\dp/theta_rega [1]),
	.D(\dp/n196 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[1]  (.Q(\dp/theta_regb [1]),
	.D(n42),
	.CLK(n21));
   DFFNEGX1 \dp/theta_rega_reg[6]  (.Q(\dp/theta_rega [6]),
	.D(\dp/n191 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[6]  (.Q(\dp/theta_regb [6]),
	.D(n47),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[6]  (.Q(\dp/x_rega [6]),
	.D(\dp/n175 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[6]  (.Q(\dp/x_regb [6]),
	.D(n31),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[5]  (.Q(\dp/x_rega [5]),
	.D(\dp/n176 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[5]  (.Q(\dp/x_regb [5]),
	.D(n30),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[4]  (.Q(\dp/x_rega [4]),
	.D(\dp/n177 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[4]  (.Q(\dp/x_regb [4]),
	.D(n29),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[3]  (.Q(\dp/x_rega [3]),
	.D(\dp/n178 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[3]  (.Q(\dp/x_regb [3]),
	.D(n28),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[2]  (.Q(\dp/x_rega [2]),
	.D(\dp/n179 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[2]  (.Q(\dp/x_regb [2]),
	.D(n27),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[1]  (.Q(\dp/x_rega [1]),
	.D(\dp/n180 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[1]  (.Q(\dp/x_regb [1]),
	.D(n26),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[0]  (.Q(\dp/x_rega [0]),
	.D(\dp/n181 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[0]  (.Q(\dp/x_regb [0]),
	.D(n25),
	.CLK(n21));
   DFFNEGX1 \dp/x_rega_reg[7]  (.Q(\dp/x_rega [7]),
	.D(\dp/n174 ),
	.CLK(clka));
   DFFNEGX1 \dp/x_regb_reg[7]  (.Q(\dp/x_regb [7]),
	.D(n32),
	.CLK(n21));
   DFFNEGX1 \dp/y_rega_reg[5]  (.Q(\dp/y_rega [5]),
	.D(\dp/n184 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[5]  (.Q(out_port1[5]),
	.D(n38),
	.CLK(n21));
   DFFNEGX1 \dp/y_rega_reg[4]  (.Q(\dp/y_rega [4]),
	.D(\dp/n185 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[4]  (.Q(out_port1[4]),
	.D(n37),
	.CLK(n20));
   DFFNEGX1 \dp/y_rega_reg[3]  (.Q(\dp/y_rega [3]),
	.D(\dp/n186 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[3]  (.Q(out_port1[3]),
	.D(n36),
	.CLK(n20));
   DFFNEGX1 \dp/y_rega_reg[2]  (.Q(\dp/y_rega [2]),
	.D(\dp/n187 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[2]  (.Q(out_port1[2]),
	.D(n35),
	.CLK(n20));
   DFFNEGX1 \dp/y_rega_reg[1]  (.Q(\dp/y_rega [1]),
	.D(\dp/n188 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[1]  (.Q(out_port1[1]),
	.D(n34),
	.CLK(n20));
   DFFNEGX1 \dp/y_rega_reg[0]  (.Q(\dp/y_rega [0]),
	.D(\dp/n189 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[0]  (.Q(out_port1[0]),
	.D(n33),
	.CLK(n20));
   DFFNEGX1 \dp/y_rega_reg[6]  (.Q(\dp/y_rega [6]),
	.D(\dp/n183 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[6]  (.Q(out_port1[6]),
	.D(n39),
	.CLK(n20));
   DFFNEGX1 \dp/y_rega_reg[7]  (.Q(\dp/y_rega [7]),
	.D(\dp/n182 ),
	.CLK(clka));
   DFFNEGX1 \dp/y_regb_reg[7]  (.Q(out_port1[7]),
	.D(n40),
	.CLK(n20));
   DFFNEGX1 \dp/theta_rega_reg[7]  (.Q(\dp/theta_rega [7]),
	.D(\dp/n190 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[7]  (.Q(\dp/theta_regb [7]),
	.D(n48),
	.CLK(n20));
   DFFNEGX1 \dp/theta_rega_reg[0]  (.Q(\dp/theta_rega [0]),
	.D(\dp/n197 ),
	.CLK(clka));
   DFFNEGX1 \dp/theta_regb_reg[0]  (.Q(\dp/theta_regb [0]),
	.D(n41),
	.CLK(n20));
   DFFNEGX1 \dp/next_counter_reg[3]  (.Q(\dp/next_counter [3]),
	.D(counter[3]),
	.CLK(n20));
   DFFNEGX1 \dp/counter_reg[3]  (.Q(counter[3]),
	.D(\dp/N119 ),
	.CLK(clka));
   DFFNEGX1 \dp/next_counter_reg[2]  (.Q(\dp/next_counter [2]),
	.D(counter[2]),
	.CLK(n20));
   DFFNEGX1 \dp/counter_reg[2]  (.Q(counter[2]),
	.D(\dp/N118 ),
	.CLK(clka));
   DFFNEGX1 \dp/next_counter_reg[1]  (.Q(\dp/next_counter [1]),
	.D(counter[1]),
	.CLK(n20));
   DFFNEGX1 \dp/counter_reg[1]  (.Q(counter[1]),
	.D(\dp/N117 ),
	.CLK(clka));
   DFFNEGX1 \dp/counter_reg[0]  (.Q(counter[0]),
	.D(\dp/N116 ),
	.CLK(clka));
   DFFNEGX1 \dp/next_counter_reg[0]  (.Q(\dp/next_counter [0]),
	.D(counter[0]),
	.CLK(n20));
   FAX1 \dp/sub_72/U2_1  (.YS(\dp/N132 ),
	.YC(\dp/sub_72/carry [2]),
	.C(\dp/sub_72/carry [1]),
	.B(n96),
	.A(\dp/x_rega [1]));
   FAX1 \dp/sub_72/U2_2  (.YS(\dp/N133 ),
	.YC(\dp/sub_72/carry [3]),
	.C(\dp/sub_72/carry [2]),
	.B(n95),
	.A(\dp/x_rega [2]));
   FAX1 \dp/sub_72/U2_3  (.YS(\dp/N134 ),
	.YC(\dp/sub_72/carry [4]),
	.C(\dp/sub_72/carry [3]),
	.B(n99),
	.A(\dp/x_rega [3]));
   FAX1 \dp/sub_72/U2_4  (.YS(\dp/N135 ),
	.YC(\dp/sub_72/carry [5]),
	.C(\dp/sub_72/carry [4]),
	.B(n93),
	.A(\dp/x_rega [4]));
   FAX1 \dp/sub_72/U2_5  (.YS(\dp/N136 ),
	.YC(\dp/sub_72/carry [6]),
	.C(\dp/sub_72/carry [5]),
	.B(n97),
	.A(\dp/x_rega [5]));
   FAX1 \dp/sub_72/U2_6  (.YS(\dp/N137 ),
	.YC(\dp/sub_72/carry [7]),
	.C(\dp/sub_72/carry [6]),
	.B(n106),
	.A(\dp/x_rega [6]));
   FAX1 \dp/sub_72/U2_7  (.YS(\dp/N138 ),
	.YC(),
	.C(\dp/sub_72/carry [7]),
	.B(n109),
	.A(\dp/x_rega [7]));
   FAX1 \dp/add_73/U1_1  (.YS(\dp/N148 ),
	.YC(\dp/add_73/carry [2]),
	.C(n3),
	.B(\dp/N140 ),
	.A(\dp/y_rega [1]));
   FAX1 \dp/add_73/U1_2  (.YS(\dp/N149 ),
	.YC(\dp/add_73/carry [3]),
	.C(\dp/add_73/carry [2]),
	.B(\dp/N141 ),
	.A(\dp/y_rega [2]));
   FAX1 \dp/add_73/U1_3  (.YS(\dp/N150 ),
	.YC(\dp/add_73/carry [4]),
	.C(\dp/add_73/carry [3]),
	.B(\dp/N142 ),
	.A(\dp/y_rega [3]));
   FAX1 \dp/add_73/U1_4  (.YS(\dp/N151 ),
	.YC(\dp/add_73/carry [5]),
	.C(\dp/add_73/carry [4]),
	.B(\dp/N143 ),
	.A(\dp/y_rega [4]));
   FAX1 \dp/add_73/U1_5  (.YS(\dp/N152 ),
	.YC(\dp/add_73/carry [6]),
	.C(\dp/add_73/carry [5]),
	.B(\dp/N144 ),
	.A(\dp/y_rega [5]));
   FAX1 \dp/add_73/U1_6  (.YS(\dp/N153 ),
	.YC(\dp/add_73/carry [7]),
	.C(\dp/add_73/carry [6]),
	.B(\dp/N145 ),
	.A(\dp/y_rega [6]));
   FAX1 \dp/add_73/U1_7  (.YS(\dp/N154 ),
	.YC(),
	.C(\dp/add_73/carry [7]),
	.B(\dp/N146 ),
	.A(\dp/y_rega [7]));
   FAX1 \dp/sub_74/U2_1  (.YS(\dp/N156 ),
	.YC(\dp/sub_74/carry [2]),
	.C(\dp/sub_74/carry [1]),
	.B(n118),
	.A(\dp/theta_rega [1]));
   FAX1 \dp/sub_74/U2_2  (.YS(\dp/N157 ),
	.YC(\dp/sub_74/carry [3]),
	.C(\dp/sub_74/carry [2]),
	.B(n117),
	.A(\dp/theta_rega [2]));
   FAX1 \dp/sub_74/U2_3  (.YS(\dp/N158 ),
	.YC(\dp/sub_74/carry [4]),
	.C(\dp/sub_74/carry [3]),
	.B(\dp/n135 ),
	.A(\dp/theta_rega [3]));
   FAX1 \dp/sub_74/U2_4  (.YS(\dp/N159 ),
	.YC(\dp/sub_74/carry [5]),
	.C(\dp/sub_74/carry [4]),
	.B(n120),
	.A(\dp/theta_rega [4]));
   FAX1 \dp/sub_74/U2_5  (.YS(\dp/N160 ),
	.YC(\dp/sub_74/carry [6]),
	.C(\dp/sub_74/carry [5]),
	.B(\dp/n132 ),
	.A(\dp/theta_rega [5]));
   FAX1 \dp/add_77/U1_1  (.YS(\dp/N172 ),
	.YC(\dp/add_77/carry [2]),
	.C(n2),
	.B(\dp/N124 ),
	.A(\dp/x_rega [1]));
   FAX1 \dp/add_77/U1_2  (.YS(\dp/N173 ),
	.YC(\dp/add_77/carry [3]),
	.C(\dp/add_77/carry [2]),
	.B(\dp/N125 ),
	.A(\dp/x_rega [2]));
   FAX1 \dp/add_77/U1_3  (.YS(\dp/N174 ),
	.YC(\dp/add_77/carry [4]),
	.C(\dp/add_77/carry [3]),
	.B(\dp/N126 ),
	.A(\dp/x_rega [3]));
   FAX1 \dp/add_77/U1_4  (.YS(\dp/N175 ),
	.YC(\dp/add_77/carry [5]),
	.C(\dp/add_77/carry [4]),
	.B(\dp/N127 ),
	.A(\dp/x_rega [4]));
   FAX1 \dp/add_77/U1_5  (.YS(\dp/N176 ),
	.YC(\dp/add_77/carry [6]),
	.C(\dp/add_77/carry [5]),
	.B(\dp/N128 ),
	.A(\dp/x_rega [5]));
   FAX1 \dp/add_77/U1_6  (.YS(\dp/N177 ),
	.YC(\dp/add_77/carry [7]),
	.C(\dp/add_77/carry [6]),
	.B(\dp/N129 ),
	.A(\dp/x_rega [6]));
   FAX1 \dp/add_77/U1_7  (.YS(\dp/N178 ),
	.YC(),
	.C(\dp/add_77/carry [7]),
	.B(\dp/N130 ),
	.A(\dp/x_rega [7]));
   FAX1 \dp/sub_78/U2_1  (.YS(\dp/N188 ),
	.YC(\dp/sub_78/carry [2]),
	.C(\dp/sub_78/carry [1]),
	.B(n81),
	.A(\dp/y_rega [1]));
   FAX1 \dp/sub_78/U2_2  (.YS(\dp/N189 ),
	.YC(\dp/sub_78/carry [3]),
	.C(\dp/sub_78/carry [2]),
	.B(n78),
	.A(\dp/y_rega [2]));
   FAX1 \dp/sub_78/U2_3  (.YS(\dp/N190 ),
	.YC(\dp/sub_78/carry [4]),
	.C(\dp/sub_78/carry [3]),
	.B(n84),
	.A(\dp/y_rega [3]));
   FAX1 \dp/sub_78/U2_4  (.YS(\dp/N191 ),
	.YC(\dp/sub_78/carry [5]),
	.C(\dp/sub_78/carry [4]),
	.B(n76),
	.A(\dp/y_rega [4]));
   FAX1 \dp/sub_78/U2_5  (.YS(\dp/N192 ),
	.YC(\dp/sub_78/carry [6]),
	.C(\dp/sub_78/carry [5]),
	.B(n82),
	.A(\dp/y_rega [5]));
   FAX1 \dp/sub_78/U2_6  (.YS(\dp/N193 ),
	.YC(\dp/sub_78/carry [7]),
	.C(\dp/sub_78/carry [6]),
	.B(n79),
	.A(\dp/y_rega [6]));
   FAX1 \dp/sub_78/U2_7  (.YS(\dp/N194 ),
	.YC(),
	.C(\dp/sub_78/carry [7]),
	.B(n89),
	.A(\dp/y_rega [7]));
   FAX1 \dp/add_79/U1_1  (.YS(\dp/N196 ),
	.YC(\dp/add_79/carry [2]),
	.C(n4),
	.B(\dp/ROM_VALUE [1]),
	.A(\dp/theta_rega [1]));
   FAX1 \dp/add_79/U1_2  (.YS(\dp/N197 ),
	.YC(\dp/add_79/carry [3]),
	.C(\dp/add_79/carry [2]),
	.B(\dp/ROM_VALUE [2]),
	.A(\dp/theta_rega [2]));
   FAX1 \dp/add_79/U1_3  (.YS(\dp/N198 ),
	.YC(\dp/add_79/carry [4]),
	.C(\dp/add_79/carry [3]),
	.B(n116),
	.A(\dp/theta_rega [3]));
   FAX1 \dp/add_79/U1_4  (.YS(\dp/N199 ),
	.YC(\dp/add_79/carry [5]),
	.C(\dp/add_79/carry [4]),
	.B(\dp/ROM_VALUE [4]),
	.A(\dp/theta_rega [4]));
   FAX1 \dp/add_79/U1_5  (.YS(\dp/N200 ),
	.YC(\dp/add_79/carry [6]),
	.C(\dp/add_79/carry [5]),
	.B(n119),
	.A(\dp/theta_rega [5]));
   AND2X2 U1 (.Y(n1),
	.B(n57),
	.A(in_mux_ctl[1]));
   AND2X2 U2 (.Y(n2),
	.B(\dp/x_rega [0]),
	.A(\dp/N123 ));
   AND2X2 U3 (.Y(n3),
	.B(\dp/y_rega [0]),
	.A(\dp/N139 ));
   AND2X2 U4 (.Y(n4),
	.B(\dp/theta_rega [0]),
	.A(\dp/ROM_VALUE [0]));
   AND2X2 U5 (.Y(n5),
	.B(\dp/theta_rega [6]),
	.A(\dp/add_79/carry [6]));
   INVX2 U6 (.Y(n8),
	.A(\dp/n107 ));
   INVX2 U7 (.Y(n13),
	.A(n15));
   INVX2 U8 (.Y(n20),
	.A(n22));
   INVX2 U9 (.Y(n21),
	.A(n22));
   BUFX2 U10 (.Y(n15),
	.A(n19));
   BUFX2 U11 (.Y(n14),
	.A(n19));
   BUFX2 U12 (.Y(n17),
	.A(n19));
   BUFX2 U13 (.Y(n16),
	.A(n19));
   BUFX2 U14 (.Y(n18),
	.A(n19));
   INVX2 U15 (.Y(n12),
	.A(n6));
   INVX2 U16 (.Y(n7),
	.A(cordic_mode));
   INVX2 U17 (.Y(n123),
	.A(counter[0]));
   INVX2 U18 (.Y(n9),
	.A(counter[1]));
   INVX2 U19 (.Y(n11),
	.A(counter[3]));
   INVX2 U20 (.Y(n10),
	.A(counter[2]));
   INVX2 U21 (.Y(n22),
	.A(clkb));
   OR2X1 U22 (.Y(n6),
	.B(in_mux_ctl[1]),
	.A(n57));
   INVX2 U23 (.Y(n19),
	.A(\dp/n142 ));
   OR2X1 U24 (.Y(\dp/sub_72/carry [1]),
	.B(n92),
	.A(\dp/x_rega [0]));
   XNOR2X1 U25 (.Y(\dp/N131 ),
	.B(\dp/x_rega [0]),
	.A(n92));
   OR2X1 U26 (.Y(\dp/sub_74/carry [7]),
	.B(\dp/sub_74/carry [6]),
	.A(\dp/theta_rega [6]));
   XNOR2X1 U27 (.Y(\dp/N161 ),
	.B(\dp/theta_rega [6]),
	.A(\dp/sub_74/carry [6]));
   XNOR2X1 U28 (.Y(\dp/N162 ),
	.B(\dp/sub_74/carry [7]),
	.A(\dp/theta_rega [7]));
   OR2X1 U29 (.Y(\dp/sub_74/carry [1]),
	.B(n115),
	.A(\dp/theta_rega [0]));
   XNOR2X1 U30 (.Y(\dp/N155 ),
	.B(\dp/theta_rega [0]),
	.A(n115));
   OR2X1 U31 (.Y(\dp/sub_78/carry [1]),
	.B(n75),
	.A(\dp/y_rega [0]));
   XNOR2X1 U32 (.Y(\dp/N187 ),
	.B(\dp/y_rega [0]),
	.A(n75));
   XOR2X1 U33 (.Y(\dp/N147 ),
	.B(\dp/y_rega [0]),
	.A(\dp/N139 ));
   XOR2X1 U34 (.Y(\dp/N171 ),
	.B(\dp/x_rega [0]),
	.A(\dp/N123 ));
   XOR2X1 U35 (.Y(\dp/N195 ),
	.B(\dp/theta_rega [0]),
	.A(\dp/ROM_VALUE [0]));
   XOR2X1 U36 (.Y(\dp/N201 ),
	.B(\dp/theta_rega [6]),
	.A(\dp/add_79/carry [6]));
   XOR2X1 U37 (.Y(\dp/N202 ),
	.B(n5),
	.A(\dp/theta_rega [7]));
   OR2X2 U38 (.Y(\dp/n124 ),
	.B(n1),
	.A(n12));
   INVX2 U39 (.Y(n23),
	.A(\fsm/n25 ));
   INVX2 U40 (.Y(n24),
	.A(reset));
   INVX2 U41 (.Y(n25),
	.A(\dp/n165 ));
   INVX2 U42 (.Y(n26),
	.A(\dp/n164 ));
   INVX2 U43 (.Y(n27),
	.A(\dp/n163 ));
   INVX2 U44 (.Y(n28),
	.A(\dp/n162 ));
   INVX2 U45 (.Y(n29),
	.A(\dp/n161 ));
   INVX2 U46 (.Y(n30),
	.A(\dp/n160 ));
   INVX2 U47 (.Y(n31),
	.A(\dp/n159 ));
   INVX2 U48 (.Y(n32),
	.A(\dp/n158 ));
   INVX2 U49 (.Y(n33),
	.A(\dp/n157 ));
   INVX2 U50 (.Y(n34),
	.A(\dp/n156 ));
   INVX2 U51 (.Y(n35),
	.A(\dp/n155 ));
   INVX2 U52 (.Y(n36),
	.A(\dp/n154 ));
   INVX2 U53 (.Y(n37),
	.A(\dp/n153 ));
   INVX2 U54 (.Y(n38),
	.A(\dp/n152 ));
   INVX2 U55 (.Y(n39),
	.A(\dp/n151 ));
   INVX2 U56 (.Y(n40),
	.A(\dp/n150 ));
   INVX2 U57 (.Y(n41),
	.A(\dp/n149 ));
   INVX2 U58 (.Y(n42),
	.A(\dp/n148 ));
   INVX2 U59 (.Y(n43),
	.A(\dp/n147 ));
   INVX2 U60 (.Y(n44),
	.A(\dp/n146 ));
   INVX2 U61 (.Y(n45),
	.A(\dp/n145 ));
   INVX2 U62 (.Y(n46),
	.A(\dp/n144 ));
   INVX2 U63 (.Y(n47),
	.A(\dp/n143 ));
   INVX2 U64 (.Y(n48),
	.A(\dp/n141 ));
   INVX2 U65 (.Y(out_port0[0]),
	.A(\dp/n98 ));
   INVX2 U66 (.Y(out_port0[1]),
	.A(\dp/n97 ));
   INVX2 U67 (.Y(out_port0[2]),
	.A(\dp/n96 ));
   INVX2 U68 (.Y(out_port0[3]),
	.A(\dp/n95 ));
   INVX2 U69 (.Y(out_port0[4]),
	.A(\dp/n94 ));
   INVX2 U70 (.Y(out_port0[5]),
	.A(\dp/n93 ));
   INVX2 U71 (.Y(out_port0[6]),
	.A(\dp/n92 ));
   INVX2 U72 (.Y(out_port0[7]),
	.A(\dp/n91 ));
   INVX2 U73 (.Y(n57),
	.A(in_mux_ctl[0]));
   INVX2 U74 (.Y(n58),
	.A(\dp/n169 ));
   INVX2 U75 (.Y(n59),
	.A(counter_rst));
   INVX2 U76 (.Y(n60),
	.A(\dp/n168 ));
   INVX2 U77 (.Y(n61),
	.A(\dp/n170 ));
   INVX2 U78 (.Y(n62),
	.A(\fsm/next_state [1]));
   INVX2 U79 (.Y(n63),
	.A(\fsm/n12 ));
   INVX2 U80 (.Y(n64),
	.A(\fsm/state[1] ));
   INVX2 U81 (.Y(n65),
	.A(\fsm/next_state [0]));
   INVX2 U82 (.Y(n66),
	.A(\fsm/state[2] ));
   INVX2 U83 (.Y(n67),
	.A(\fsm/next_state [2]));
   INVX2 U84 (.Y(n68),
	.A(\fsm/state[0] ));
   INVX2 U85 (.Y(n69),
	.A(\dp/theta_rega [5]));
   INVX2 U86 (.Y(n70),
	.A(\dp/theta_rega [4]));
   INVX2 U87 (.Y(n71),
	.A(\dp/theta_rega [3]));
   INVX2 U88 (.Y(n72),
	.A(\dp/theta_rega [2]));
   INVX2 U89 (.Y(n73),
	.A(\dp/theta_rega [1]));
   INVX2 U90 (.Y(n74),
	.A(\dp/theta_rega [6]));
   INVX2 U91 (.Y(n75),
	.A(\dp/N139 ));
   INVX2 U92 (.Y(n76),
	.A(\dp/N143 ));
   INVX2 U93 (.Y(n77),
	.A(n141));
   INVX2 U94 (.Y(n78),
	.A(\dp/N141 ));
   INVX2 U95 (.Y(n79),
	.A(\dp/N145 ));
   INVX2 U96 (.Y(n80),
	.A(n143));
   INVX2 U97 (.Y(n81),
	.A(\dp/N140 ));
   INVX2 U98 (.Y(n82),
	.A(\dp/N144 ));
   INVX2 U99 (.Y(n83),
	.A(n142));
   INVX2 U100 (.Y(n84),
	.A(\dp/N142 ));
   INVX2 U101 (.Y(n85),
	.A(\dp/x_rega [6]));
   INVX2 U102 (.Y(n86),
	.A(\dp/x_rega [4]));
   INVX2 U103 (.Y(n87),
	.A(\dp/x_rega [3]));
   INVX2 U104 (.Y(n88),
	.A(\dp/x_rega [0]));
   INVX2 U105 (.Y(n89),
	.A(\dp/N146 ));
   INVX2 U106 (.Y(n90),
	.A(n144));
   INVX2 U107 (.Y(n91),
	.A(\dp/x_rega [7]));
   INVX2 U108 (.Y(n92),
	.A(\dp/N123 ));
   INVX2 U109 (.Y(n93),
	.A(\dp/N127 ));
   INVX2 U110 (.Y(n94),
	.A(n162));
   INVX2 U111 (.Y(n95),
	.A(\dp/N125 ));
   INVX2 U112 (.Y(n96),
	.A(\dp/N124 ));
   INVX2 U113 (.Y(n97),
	.A(\dp/N128 ));
   INVX2 U114 (.Y(n98),
	.A(n163));
   INVX2 U115 (.Y(n99),
	.A(\dp/N126 ));
   INVX2 U116 (.Y(n100),
	.A(\dp/y_rega [5]));
   INVX2 U117 (.Y(n101),
	.A(\dp/y_rega [4]));
   INVX2 U118 (.Y(n102),
	.A(\dp/y_rega [3]));
   INVX2 U119 (.Y(n103),
	.A(\dp/y_rega [2]));
   INVX2 U120 (.Y(n104),
	.A(\dp/y_rega [1]));
   INVX2 U121 (.Y(n105),
	.A(\dp/y_rega [0]));
   INVX2 U122 (.Y(n106),
	.A(\dp/N129 ));
   INVX2 U123 (.Y(n107),
	.A(n164));
   INVX2 U124 (.Y(n108),
	.A(\dp/y_rega [6]));
   INVX2 U125 (.Y(n109),
	.A(\dp/N130 ));
   INVX2 U126 (.Y(n110),
	.A(n165));
   INVX2 U127 (.Y(n111),
	.A(\dp/y_rega [7]));
   INVX2 U128 (.Y(n112),
	.A(\dp/theta_rega [7]));
   INVX2 U129 (.Y(n113),
	.A(\dp/theta_rega [0]));
   INVX2 U130 (.Y(n114),
	.A(\dp/next_counter [3]));
   INVX2 U131 (.Y(n115),
	.A(\dp/ROM_VALUE [0]));
   INVX2 U132 (.Y(n116),
	.A(\dp/n135 ));
   INVX2 U133 (.Y(n117),
	.A(\dp/ROM_VALUE [2]));
   INVX2 U134 (.Y(n118),
	.A(\dp/ROM_VALUE [1]));
   INVX2 U135 (.Y(n119),
	.A(\dp/n132 ));
   INVX2 U136 (.Y(n120),
	.A(\dp/ROM_VALUE [4]));
   INVX2 U137 (.Y(n121),
	.A(\dp/next_counter [2]));
   INVX2 U138 (.Y(n122),
	.A(\dp/next_counter [1]));
   INVX2 U139 (.Y(n124),
	.A(\dp/next_counter [0]));
   MUX2X1 U140 (.Y(n125),
	.S(n123),
	.B(\dp/x_rega [1]),
	.A(\dp/x_rega [0]));
   MUX2X1 U141 (.Y(n132),
	.S(n123),
	.B(\dp/x_rega [3]),
	.A(\dp/x_rega [2]));
   MUX2X1 U142 (.Y(n126),
	.S(counter[1]),
	.B(n125),
	.A(n132));
   MUX2X1 U143 (.Y(n131),
	.S(n123),
	.B(\dp/x_rega [5]),
	.A(\dp/x_rega [4]));
   MUX2X1 U144 (.Y(n133),
	.S(n123),
	.B(\dp/x_rega [7]),
	.A(\dp/x_rega [6]));
   MUX2X1 U145 (.Y(n141),
	.S(counter[1]),
	.B(n131),
	.A(n133));
   MUX2X1 U146 (.Y(n127),
	.S(counter[2]),
	.B(n126),
	.A(n141));
   NOR2X1 U147 (.Y(\dp/N139 ),
	.B(n127),
	.A(counter[3]));
   MUX2X1 U148 (.Y(n128),
	.S(n123),
	.B(\dp/x_rega [2]),
	.A(\dp/x_rega [1]));
   MUX2X1 U149 (.Y(n137),
	.S(n123),
	.B(\dp/x_rega [4]),
	.A(\dp/x_rega [3]));
   MUX2X1 U150 (.Y(n129),
	.S(counter[1]),
	.B(n128),
	.A(n137));
   MUX2X1 U151 (.Y(n136),
	.S(n123),
	.B(\dp/x_rega [6]),
	.A(\dp/x_rega [5]));
   NAND2X1 U152 (.Y(n138),
	.B(n123),
	.A(\dp/x_rega [7]));
   MUX2X1 U153 (.Y(n142),
	.S(counter[1]),
	.B(n136),
	.A(n138));
   MUX2X1 U154 (.Y(n130),
	.S(counter[2]),
	.B(n129),
	.A(n142));
   NOR2X1 U155 (.Y(\dp/N140 ),
	.B(n130),
	.A(counter[3]));
   MUX2X1 U156 (.Y(n134),
	.S(counter[1]),
	.B(n132),
	.A(n131));
   NOR2X1 U157 (.Y(n143),
	.B(counter[1]),
	.A(n133));
   MUX2X1 U158 (.Y(n135),
	.S(counter[2]),
	.B(n134),
	.A(n143));
   NOR2X1 U159 (.Y(\dp/N141 ),
	.B(n135),
	.A(counter[3]));
   MUX2X1 U160 (.Y(n139),
	.S(counter[1]),
	.B(n137),
	.A(n136));
   NOR2X1 U161 (.Y(n144),
	.B(counter[1]),
	.A(n138));
   MUX2X1 U162 (.Y(n140),
	.S(counter[2]),
	.B(n139),
	.A(n144));
   NOR2X1 U163 (.Y(\dp/N142 ),
	.B(n140),
	.A(counter[3]));
   NAND2X1 U164 (.Y(n145),
	.B(n11),
	.A(n10));
   NOR2X1 U165 (.Y(\dp/N143 ),
	.B(n145),
	.A(n77));
   NOR2X1 U166 (.Y(\dp/N144 ),
	.B(n145),
	.A(n83));
   NOR2X1 U167 (.Y(\dp/N145 ),
	.B(n145),
	.A(n80));
   NOR2X1 U168 (.Y(\dp/N146 ),
	.B(n145),
	.A(n90));
   MUX2X1 U169 (.Y(n146),
	.S(n123),
	.B(\dp/y_rega [1]),
	.A(\dp/y_rega [0]));
   MUX2X1 U170 (.Y(n153),
	.S(n123),
	.B(\dp/y_rega [3]),
	.A(\dp/y_rega [2]));
   MUX2X1 U171 (.Y(n147),
	.S(counter[1]),
	.B(n146),
	.A(n153));
   MUX2X1 U172 (.Y(n152),
	.S(n123),
	.B(\dp/y_rega [5]),
	.A(\dp/y_rega [4]));
   MUX2X1 U173 (.Y(n154),
	.S(n123),
	.B(\dp/y_rega [7]),
	.A(\dp/y_rega [6]));
   MUX2X1 U174 (.Y(n162),
	.S(counter[1]),
	.B(n152),
	.A(n154));
   MUX2X1 U175 (.Y(n148),
	.S(counter[2]),
	.B(n147),
	.A(n162));
   NOR2X1 U176 (.Y(\dp/N123 ),
	.B(n148),
	.A(counter[3]));
   MUX2X1 U177 (.Y(n149),
	.S(n123),
	.B(\dp/y_rega [2]),
	.A(\dp/y_rega [1]));
   MUX2X1 U178 (.Y(n158),
	.S(n123),
	.B(\dp/y_rega [4]),
	.A(\dp/y_rega [3]));
   MUX2X1 U179 (.Y(n150),
	.S(counter[1]),
	.B(n149),
	.A(n158));
   MUX2X1 U180 (.Y(n157),
	.S(n123),
	.B(\dp/y_rega [6]),
	.A(\dp/y_rega [5]));
   NAND2X1 U181 (.Y(n159),
	.B(n123),
	.A(\dp/y_rega [7]));
   MUX2X1 U182 (.Y(n163),
	.S(counter[1]),
	.B(n157),
	.A(n159));
   MUX2X1 U183 (.Y(n151),
	.S(counter[2]),
	.B(n150),
	.A(n163));
   NOR2X1 U184 (.Y(\dp/N124 ),
	.B(n151),
	.A(counter[3]));
   MUX2X1 U185 (.Y(n155),
	.S(counter[1]),
	.B(n153),
	.A(n152));
   NOR2X1 U186 (.Y(n164),
	.B(counter[1]),
	.A(n154));
   MUX2X1 U187 (.Y(n156),
	.S(counter[2]),
	.B(n155),
	.A(n164));
   NOR2X1 U188 (.Y(\dp/N125 ),
	.B(n156),
	.A(counter[3]));
   MUX2X1 U189 (.Y(n160),
	.S(counter[1]),
	.B(n158),
	.A(n157));
   NOR2X1 U190 (.Y(n165),
	.B(counter[1]),
	.A(n159));
   MUX2X1 U191 (.Y(n161),
	.S(counter[2]),
	.B(n160),
	.A(n165));
   NOR2X1 U192 (.Y(\dp/N126 ),
	.B(n161),
	.A(counter[3]));
   NAND2X1 U193 (.Y(n166),
	.B(n11),
	.A(n10));
   NOR2X1 U194 (.Y(\dp/N127 ),
	.B(n166),
	.A(n94));
   NOR2X1 U195 (.Y(\dp/N128 ),
	.B(n166),
	.A(n98));
   NOR2X1 U196 (.Y(\dp/N129 ),
	.B(n166),
	.A(n107));
   NOR2X1 U197 (.Y(\dp/N130 ),
	.B(n166),
	.A(n110));
endmodule

